# inherit_from: .rubocop_todo.yml
require: rubocop-rails
require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5.1
  Exclude:
    - db/schema.rb
    - db/migrate/*
    - bin/*

Rails:
  Enabled: true

Lint/AmbiguousOperator:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Style/AccessModifierDeclarations:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
