 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/buisenesses", type: :request do
  # Buiseness. As you add validations to Buiseness, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Buiseness.create! valid_attributes
      get buisenesses_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      buiseness = Buiseness.create! valid_attributes
      get buiseness_url(buiseness)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_buiseness_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      buiseness = Buiseness.create! valid_attributes
      get edit_buiseness_url(buiseness)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Buiseness" do
        expect {
          post buisenesses_url, params: { buiseness: valid_attributes }
        }.to change(Buiseness, :count).by(1)
      end

      it "redirects to the created buiseness" do
        post buisenesses_url, params: { buiseness: valid_attributes }
        expect(response).to redirect_to(buiseness_url(Buiseness.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Buiseness" do
        expect {
          post buisenesses_url, params: { buiseness: invalid_attributes }
        }.to change(Buiseness, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post buisenesses_url, params: { buiseness: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested buiseness" do
        buiseness = Buiseness.create! valid_attributes
        patch buiseness_url(buiseness), params: { buiseness: new_attributes }
        buiseness.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the buiseness" do
        buiseness = Buiseness.create! valid_attributes
        patch buiseness_url(buiseness), params: { buiseness: new_attributes }
        buiseness.reload
        expect(response).to redirect_to(buiseness_url(buiseness))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        buiseness = Buiseness.create! valid_attributes
        patch buiseness_url(buiseness), params: { buiseness: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested buiseness" do
      buiseness = Buiseness.create! valid_attributes
      expect {
        delete buiseness_url(buiseness)
      }.to change(Buiseness, :count).by(-1)
    end

    it "redirects to the buisenesses list" do
      buiseness = Buiseness.create! valid_attributes
      delete buiseness_url(buiseness)
      expect(response).to redirect_to(buisenesses_url)
    end
  end
end
