 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/change_request_mappings", type: :request do
  # ChangeRequestMapping. As you add validations to ChangeRequestMapping, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ChangeRequestMapping.create! valid_attributes
      get change_request_mappings_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      change_request_mapping = ChangeRequestMapping.create! valid_attributes
      get change_request_mapping_url(change_request_mapping)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_change_request_mapping_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      change_request_mapping = ChangeRequestMapping.create! valid_attributes
      get edit_change_request_mapping_url(change_request_mapping)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ChangeRequestMapping" do
        expect {
          post change_request_mappings_url, params: { change_request_mapping: valid_attributes }
        }.to change(ChangeRequestMapping, :count).by(1)
      end

      it "redirects to the created change_request_mapping" do
        post change_request_mappings_url, params: { change_request_mapping: valid_attributes }
        expect(response).to redirect_to(change_request_mapping_url(ChangeRequestMapping.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ChangeRequestMapping" do
        expect {
          post change_request_mappings_url, params: { change_request_mapping: invalid_attributes }
        }.to change(ChangeRequestMapping, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post change_request_mappings_url, params: { change_request_mapping: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested change_request_mapping" do
        change_request_mapping = ChangeRequestMapping.create! valid_attributes
        patch change_request_mapping_url(change_request_mapping), params: { change_request_mapping: new_attributes }
        change_request_mapping.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the change_request_mapping" do
        change_request_mapping = ChangeRequestMapping.create! valid_attributes
        patch change_request_mapping_url(change_request_mapping), params: { change_request_mapping: new_attributes }
        change_request_mapping.reload
        expect(response).to redirect_to(change_request_mapping_url(change_request_mapping))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        change_request_mapping = ChangeRequestMapping.create! valid_attributes
        patch change_request_mapping_url(change_request_mapping), params: { change_request_mapping: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested change_request_mapping" do
      change_request_mapping = ChangeRequestMapping.create! valid_attributes
      expect {
        delete change_request_mapping_url(change_request_mapping)
      }.to change(ChangeRequestMapping, :count).by(-1)
    end

    it "redirects to the change_request_mappings list" do
      change_request_mapping = ChangeRequestMapping.create! valid_attributes
      delete change_request_mapping_url(change_request_mapping)
      expect(response).to redirect_to(change_request_mappings_url)
    end
  end
end
