 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/fifty_five_hundreds", type: :request do
  # FiftyFiveHundred. As you add validations to FiftyFiveHundred, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      FiftyFiveHundred.create! valid_attributes
      get fifty_five_hundreds_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      fifty_five_hundred = FiftyFiveHundred.create! valid_attributes
      get fifty_five_hundred_url(fifty_five_hundred)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_fifty_five_hundred_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      fifty_five_hundred = FiftyFiveHundred.create! valid_attributes
      get edit_fifty_five_hundred_url(fifty_five_hundred)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new FiftyFiveHundred" do
        expect {
          post fifty_five_hundreds_url, params: { fifty_five_hundred: valid_attributes }
        }.to change(FiftyFiveHundred, :count).by(1)
      end

      it "redirects to the created fifty_five_hundred" do
        post fifty_five_hundreds_url, params: { fifty_five_hundred: valid_attributes }
        expect(response).to redirect_to(fifty_five_hundred_url(FiftyFiveHundred.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new FiftyFiveHundred" do
        expect {
          post fifty_five_hundreds_url, params: { fifty_five_hundred: invalid_attributes }
        }.to change(FiftyFiveHundred, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post fifty_five_hundreds_url, params: { fifty_five_hundred: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested fifty_five_hundred" do
        fifty_five_hundred = FiftyFiveHundred.create! valid_attributes
        patch fifty_five_hundred_url(fifty_five_hundred), params: { fifty_five_hundred: new_attributes }
        fifty_five_hundred.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the fifty_five_hundred" do
        fifty_five_hundred = FiftyFiveHundred.create! valid_attributes
        patch fifty_five_hundred_url(fifty_five_hundred), params: { fifty_five_hundred: new_attributes }
        fifty_five_hundred.reload
        expect(response).to redirect_to(fifty_five_hundred_url(fifty_five_hundred))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        fifty_five_hundred = FiftyFiveHundred.create! valid_attributes
        patch fifty_five_hundred_url(fifty_five_hundred), params: { fifty_five_hundred: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested fifty_five_hundred" do
      fifty_five_hundred = FiftyFiveHundred.create! valid_attributes
      expect {
        delete fifty_five_hundred_url(fifty_five_hundred)
      }.to change(FiftyFiveHundred, :count).by(-1)
    end

    it "redirects to the fifty_five_hundreds list" do
      fifty_five_hundred = FiftyFiveHundred.create! valid_attributes
      delete fifty_five_hundred_url(fifty_five_hundred)
      expect(response).to redirect_to(fifty_five_hundreds_url)
    end
  end
end
