 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/generals", type: :request do
  # General. As you add validations to General, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      General.create! valid_attributes
      get generals_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      general = General.create! valid_attributes
      get general_url(general)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_general_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      general = General.create! valid_attributes
      get edit_general_url(general)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new General" do
        expect {
          post generals_url, params: { general: valid_attributes }
        }.to change(General, :count).by(1)
      end

      it "redirects to the created general" do
        post generals_url, params: { general: valid_attributes }
        expect(response).to redirect_to(general_url(General.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new General" do
        expect {
          post generals_url, params: { general: invalid_attributes }
        }.to change(General, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post generals_url, params: { general: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested general" do
        general = General.create! valid_attributes
        patch general_url(general), params: { general: new_attributes }
        general.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the general" do
        general = General.create! valid_attributes
        patch general_url(general), params: { general: new_attributes }
        general.reload
        expect(response).to redirect_to(general_url(general))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        general = General.create! valid_attributes
        patch general_url(general), params: { general: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested general" do
      general = General.create! valid_attributes
      expect {
        delete general_url(general)
      }.to change(General, :count).by(-1)
    end

    it "redirects to the generals list" do
      general = General.create! valid_attributes
      delete general_url(general)
      expect(response).to redirect_to(generals_url)
    end
  end
end
