 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/principals", type: :request do
  # Principal. As you add validations to Principal, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Principal.create! valid_attributes
      get principals_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      principal = Principal.create! valid_attributes
      get principal_url(principal)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_principal_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      principal = Principal.create! valid_attributes
      get edit_principal_url(principal)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Principal" do
        expect {
          post principals_url, params: { principal: valid_attributes }
        }.to change(Principal, :count).by(1)
      end

      it "redirects to the created principal" do
        post principals_url, params: { principal: valid_attributes }
        expect(response).to redirect_to(principal_url(Principal.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Principal" do
        expect {
          post principals_url, params: { principal: invalid_attributes }
        }.to change(Principal, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post principals_url, params: { principal: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested principal" do
        principal = Principal.create! valid_attributes
        patch principal_url(principal), params: { principal: new_attributes }
        principal.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the principal" do
        principal = Principal.create! valid_attributes
        patch principal_url(principal), params: { principal: new_attributes }
        principal.reload
        expect(response).to redirect_to(principal_url(principal))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        principal = Principal.create! valid_attributes
        patch principal_url(principal), params: { principal: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested principal" do
      principal = Principal.create! valid_attributes
      expect {
        delete principal_url(principal)
      }.to change(Principal, :count).by(-1)
    end

    it "redirects to the principals list" do
      principal = Principal.create! valid_attributes
      delete principal_url(principal)
      expect(response).to redirect_to(principals_url)
    end
  end
end
