 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/project_templates", type: :request do
  # ProjectTemplate. As you add validations to ProjectTemplate, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ProjectTemplate.create! valid_attributes
      get project_templates_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      project_template = ProjectTemplate.create! valid_attributes
      get project_template_url(project_template)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_project_template_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      project_template = ProjectTemplate.create! valid_attributes
      get edit_project_template_url(project_template)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ProjectTemplate" do
        expect {
          post project_templates_url, params: { project_template: valid_attributes }
        }.to change(ProjectTemplate, :count).by(1)
      end

      it "redirects to the created project_template" do
        post project_templates_url, params: { project_template: valid_attributes }
        expect(response).to redirect_to(project_template_url(ProjectTemplate.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ProjectTemplate" do
        expect {
          post project_templates_url, params: { project_template: invalid_attributes }
        }.to change(ProjectTemplate, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post project_templates_url, params: { project_template: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested project_template" do
        project_template = ProjectTemplate.create! valid_attributes
        patch project_template_url(project_template), params: { project_template: new_attributes }
        project_template.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the project_template" do
        project_template = ProjectTemplate.create! valid_attributes
        patch project_template_url(project_template), params: { project_template: new_attributes }
        project_template.reload
        expect(response).to redirect_to(project_template_url(project_template))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        project_template = ProjectTemplate.create! valid_attributes
        patch project_template_url(project_template), params: { project_template: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested project_template" do
      project_template = ProjectTemplate.create! valid_attributes
      expect {
        delete project_template_url(project_template)
      }.to change(ProjectTemplate, :count).by(-1)
    end

    it "redirects to the project_templates list" do
      project_template = ProjectTemplate.create! valid_attributes
      delete project_template_url(project_template)
      expect(response).to redirect_to(project_templates_url)
    end
  end
end
