 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/project_tasks", type: :request do
  # ProjectTask. As you add validations to ProjectTask, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ProjectTask.create! valid_attributes
      get project_tasks_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      project_task = ProjectTask.create! valid_attributes
      get project_task_url(project_task)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_project_task_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      project_task = ProjectTask.create! valid_attributes
      get edit_project_task_url(project_task)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ProjectTask" do
        expect {
          post project_tasks_url, params: { project_task: valid_attributes }
        }.to change(ProjectTask, :count).by(1)
      end

      it "redirects to the created project_task" do
        post project_tasks_url, params: { project_task: valid_attributes }
        expect(response).to redirect_to(project_task_url(ProjectTask.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ProjectTask" do
        expect {
          post project_tasks_url, params: { project_task: invalid_attributes }
        }.to change(ProjectTask, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post project_tasks_url, params: { project_task: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested project_task" do
        project_task = ProjectTask.create! valid_attributes
        patch project_task_url(project_task), params: { project_task: new_attributes }
        project_task.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the project_task" do
        project_task = ProjectTask.create! valid_attributes
        patch project_task_url(project_task), params: { project_task: new_attributes }
        project_task.reload
        expect(response).to redirect_to(project_task_url(project_task))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        project_task = ProjectTask.create! valid_attributes
        patch project_task_url(project_task), params: { project_task: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested project_task" do
      project_task = ProjectTask.create! valid_attributes
      expect {
        delete project_task_url(project_task)
      }.to change(ProjectTask, :count).by(-1)
    end

    it "redirects to the project_tasks list" do
      project_task = ProjectTask.create! valid_attributes
      delete project_task_url(project_task)
      expect(response).to redirect_to(project_tasks_url)
    end
  end
end
