 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/task_items", type: :request do
  # TaskItem. As you add validations to TaskItem, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      TaskItem.create! valid_attributes
      get task_items_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      task_item = TaskItem.create! valid_attributes
      get task_item_url(task_item)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_task_item_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      task_item = TaskItem.create! valid_attributes
      get edit_task_item_url(task_item)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new TaskItem" do
        expect {
          post task_items_url, params: { task_item: valid_attributes }
        }.to change(TaskItem, :count).by(1)
      end

      it "redirects to the created task_item" do
        post task_items_url, params: { task_item: valid_attributes }
        expect(response).to redirect_to(task_item_url(TaskItem.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new TaskItem" do
        expect {
          post task_items_url, params: { task_item: invalid_attributes }
        }.to change(TaskItem, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post task_items_url, params: { task_item: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested task_item" do
        task_item = TaskItem.create! valid_attributes
        patch task_item_url(task_item), params: { task_item: new_attributes }
        task_item.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the task_item" do
        task_item = TaskItem.create! valid_attributes
        patch task_item_url(task_item), params: { task_item: new_attributes }
        task_item.reload
        expect(response).to redirect_to(task_item_url(task_item))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        task_item = TaskItem.create! valid_attributes
        patch task_item_url(task_item), params: { task_item: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested task_item" do
      task_item = TaskItem.create! valid_attributes
      expect {
        delete task_item_url(task_item)
      }.to change(TaskItem, :count).by(-1)
    end

    it "redirects to the task_items list" do
      task_item = TaskItem.create! valid_attributes
      delete task_item_url(task_item)
      expect(response).to redirect_to(task_items_url)
    end
  end
end
