default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: 'chris'
  password: 'chris'
  port: 5432

development:
  <<: *default
  database: starter_kit

test:
  <<: *default
  database: starter_kit

production:
  <<: *default
  database: starter-kit_production
