default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: 'postgres'
  password: 'myPassword'
  port: 5432

development:
  <<: *default
  database: bei_clientportal_dev_5

# test:
#   <<: *default
#   database: bei_clientportal

# production:
#   <<: *default
#   database: bei_clientportal
